// ActivityTypes

const int ACTIVITYTYPE_GAMEDETECTOR_DIRECTED_WONSWAP_INSTALL = 14;
const int ACTIVITYTYPE_GAMEDETECTOR_DIRECTED_WONSWAP_RESOURCE_DOWNLOAD = 15;
const int ACTIVITYTYPE_GAMEDETECTOR_EXTENDED_INFO_REQUESTED = 16;
const int ACTIVITYTYPE_GAMEDETECTOR_LAUNCH = 1;
const int ACTIVITYTYPE_GAMEDETECTOR_LAUNCH_REQUESTED_BY_WONCHAT = 17;
const int ACTIVITYTYPE_GAMEDETECTOR_LIST_REFRESHED = 12;
const int ACTIVITYTYPE_GAMEDETECTOR_LOADED = 11;
const int ACTIVITYTYPE_GAMEDETECTOR_PLAYER_SEARCH_PERFORMED = 13;
const int ACTIVITYTYPE_GAMEDETECTOR_URL_BUTTON_CLICKTHROUGH = 18;
const int ACTIVITYTYPE_HALFLIFE_CLIENT_SHUTDOWN = 8;
const int ACTIVITYTYPE_HALFLIFE_CLIENT_STARTUP = 7;
const int ACTIVITYTYPE_HALFLIFE_PLAYER_JOIN = 9;
const int ACTIVITYTYPE_HALFLIFE_PLAYER_LEAVE = 10;
const int ACTIVITYTYPE_HOMEWORLD_GAME_CREATE = 2;
const int ACTIVITYTYPE_HOMEWORLD_GAME_ENTER = 3;
const int ACTIVITYTYPE_HOMEWORLD_GAME_EXIT = 4;
const int ACTIVITYTYPE_HOMEWORLD_LOBBY_ENTER = 5;
const int ACTIVITYTYPE_HOMEWORLD_LOBBY_EXIT = 6;
const int ACTIVITYTYPE_STARFLEET_COMMAND_GAME_CREATE = 19;
const int ACTIVITYTYPE_STARFLEET_COMMAND_GAME_ENTER = 20;
const int ACTIVITYTYPE_STARFLEET_COMMAND_GAME_EXIT = 21;
const int ACTIVITYTYPE_STARFLEET_COMMAND_LOBBY_ENTER = 22;
const int ACTIVITYTYPE_STARFLEET_COMMAND_LOBBY_EXIT = 23;
const int ACTIVITYTYPE_TITAN_SERVER_STATS = 24;

// ActivityTypeGroups

const int ACTIVITYTYPEGROUP_GAMEDETECTOR = 1;
const int ACTIVITYTYPEGROUP_HALFLIFE = 3;
const int ACTIVITYTYPEGROUP_HOMEWORLD = 2;
const int ACTIVITYTYPEGROUP_ROUTING_SERVER = 5;
const int ACTIVITYTYPEGROUP_STARFLEET_COMMAND = 4;

// AdminGroups


// AttachmentContentTypes

const int ATTACHMENTCONTENTTYPE_NONE = 1;

// ClientServiceTypes


// DataTypes

const int DATATYPE_NUMBER = 1;
const int DATATYPE_STRING = 2;

// ActivityHistoryDetailTypes

const int ACTIVITYHISTORYDETAILTYPE_BEHIND_FIREWALL = 6;
const int ACTIVITYHISTORYDETAILTYPE_BYTES_RECEIVED = 9;
const int ACTIVITYHISTORYDETAILTYPE_BYTES_SENT = 10;
const int ACTIVITYHISTORYDETAILTYPE_DISCONNECT_CODE = 3;
const int ACTIVITYHISTORYDETAILTYPE_HOMEWORLD_LANGUAGE = 5;
const int ACTIVITYHISTORYDETAILTYPE_MESSAGES_RECEIVED = 11;
const int ACTIVITYHISTORYDETAILTYPE_MESSAGES_SENT = 12;
const int ACTIVITYHISTORYDETAILTYPE_PLAYER_COUNT = 1;
const int ACTIVITYHISTORYDETAILTYPE_SESSION_LENGTH = 7;
const int ACTIVITYHISTORYDETAILTYPE_TIMEZONE = 2;
const int ACTIVITYHISTORYDETAILTYPE_USING_ROUTING_SERVER = 8;
const int ACTIVITYHISTORYDETAILTYPE_VERSION_STRING = 4;

// FeedbackResolutionTypes


// FeedbackTypes


// OffenseTypes


// Resources


// ServiceTypes

const int SERVICETYPE_AUTHENTICATION_SERVER = 10;
const int SERVICETYPE_CHAT_SERVER = 11;
const int SERVICETYPE_CONTEST_SERVER = 12;
const int SERVICETYPE_CREAM_SERVER = 13;
const int SERVICETYPE_DIRECTORY_SERVER = 14;
const int SERVICETYPE_EVENT_SERVER = 15;
const int SERVICETYPE_FACTORY_SERVER = 16;
const int SERVICETYPE_FIREWALL_DETECTOR = 17;
const int SERVICETYPE_HALFLIFE_SERVER = 4;
const int SERVICETYPE_HALFLIFE_SERVER_OTHER_MOD = 6;
const int SERVICETYPE_OBSERVATION_SERVER = 18;
const int SERVICETYPE_PARAMETER_SERVER = 19;
const int SERVICETYPE_PING_SERVER = 20;
const int SERVICETYPE_PROFILE_SERVER = 21;
const int SERVICETYPE_QUAKE_SERVER = 3;
const int SERVICETYPE_ROUTING_SERVER = 9;
const int SERVICETYPE_SAMPLE_SERVER = 22;
const int SERVICETYPE_STARSEIGE_SERVER = 8;
const int SERVICETYPE_TEAM_FORTRESS_CLASSIC_SERVER = 5;
const int SERVICETYPE_TRIBES_SERVER = 2;
const int SERVICETYPE_UNREAL_SERVER = 7;
const int SERVICETYPE_WEATHER_SERVER = 1;
const int SERVICETYPE_WORDOX_SERVER = 23;

// TrustLevelChangeReasons

const int TRUSTLEVELCHANGEREASON_6_MONTH_GOOD_RECORD = 2;
const int TRUSTLEVELCHANGEREASON_NEW_RECORD = 1;

// UnitOfMeasures

const int UNITOFMEASURE_BOOLEAN = 3;
const int UNITOFMEASURE_BYTES = 6;
const int UNITOFMEASURE_COUNT = 1;
const int UNITOFMEASURE_NONE_NUMBER = 4;
const int UNITOFMEASURE_NONE_STRING = 5;
const int UNITOFMEASURE_SECONDS = 2;

// UserAuthenticationMethods

const int USERAUTHENTICATIONMETHOD_AUTH1 = 1;

// UserEventTypes

const int USEREVENTTYPE_CREATE_ACCOUNT = 1;

