#define		Alpha		0
#define		Bravo		1
#define		Charlie		2
#define		Delta		3
#define		Echo		4
#define		Foxtrot		5
#define		Golf		6
#define		Hotel		7
#define		India		8
#define		Juliette	9
#define		Kilo		10
#define		Lima		11
#define		Mike		12
#define		November	13
#define		Oscar		14
#define		Papa		15
#define		Quebec		16
#define		Romeo		17
#define		Sierra		18
#define		Tango		19
#define		Uniform		20
#define		Victor		21
#define		Whiskey		22
#define		Xray		23
#define		Yankee		24
#define		Zulu		25

