#ifndef ___STRINGS_ONLY_H
#define ___STRINGS_ONLY_H

// important: do not include types.h, statscript.h, or any other game/windows include files

typedef enum
{
    strAdvanceSupportFrigate,
    strAttackBomber,
    strCarrier,
    strCloakedFighter,
    strCloakGenerator,
    strDDDFrigate,
    strDefenseFighter,
    strDFGFrigate,
    strGravWellGenerator,
    strHeavyCorvette,
    strHeavyCruiser,
    strHeavyDefender,
    strHeavyInterceptor,
    strIonCannonFrigate,
    strLightCorvette,
    strLightDefender,
    strLightInterceptor,
    strMinelayerCorvette,
    strMissileDestroyer,
    strMothership,
    strMultiGunCorvette,
    strProbe,
    strProximitySensor,
    strRepairCorvette,
    strResearchShip,
    strResourceCollector,
    strResourceController,
    strSalCapCorvette,
    strSensorArray,
    strStandardDestroyer,
    strStandardFrigate,
    strDrone,
    strTargetDrone,
    strHeadShotAsteroid,
    strCryoTray,
    strP1Fighter,
    strP1IonArrayFrigate,
    strP1MissileCorvette,
    strP1Mothership,
    strP1StandardCorvette,
    strP2AdvanceSwarmer,
    strP2FuelPod,
    strP2Mothership,
    strP2MultiBeamFrigate,
    strP2Swarmer,
    strP3Destroyer,
    strP3Frigate,
    strP3Megaship,
    strFloatingCity,
    strCargoBarge,
    strMiningBase,
    strResearchStation,
    strJunkYardDawg,
    strJunkYardHQ,
    strGhostship,
    strJunk_LGun,
    strJunk_SGun,
    strResearchStationBridge,
    strResearchStationTower,

    strCLASS_Mothership,
    strCLASS_HeavyCruiser,
    strCLASS_Carrier,
    strCLASS_Destroyer,
    strCLASS_Frigate,
    strCLASS_Corvette,
    strCLASS_Fighter,
    strCLASS_Resource,
    strCLASS_NonCombat,
    strCLASS_Class,
    strCLASS_SuperCapital,

    strPlayerUnits,
    strEnemyUnits,
    strAlliedUnits,
    strResources,
    strDerelictShip,
    strUnexplored,
    strAsteroids,
    strNebula,
    strGasClouds,
    strDustClouds,

    strLoadingShips,
    strTexturePreload,
    strLoadingTextures,

    strEnemyShip,
    strAlliedShip,
    strEnemy,
    strAllied,

    strHaveBeenDefeated,
    strQuestIsLost,
    strAllPlayersDead,
    strPlayerHasWon,
    strPlayerHasDied,
    strPlayersHaveWon,
    strHaveBeenDroppedOut,
    strAllOtherPlayersDroppedOut,
    strSyncPktQOverrun,

    strNewAlloys,
    strMassDrive1Kt,
    strCoolingSystems,
    strCloakFighter,
    strTargetingSystems,
    strPlasmaWeapons,
    strChassis1,
    strMassDrive10Kt,
    strMediumGuns,
    strMineLayerTech,
    strChassis2,
    strAdvancedCoolingSystems,
    strMassDrive100Kt,
    strFireControl,
    strSupportRefuelTech,
    strAdvanceTacticalSupport,
    strIonWeapons,
    strDDDFTech,
    strChassis3,
    strMassDrive1Mt,
    strAdvancedFireControl,
    strMissileWeapons,
    strConstructionTech,
    strHeavyGuns,
    strProximityDetector,
    strSensorsArrayTech,
    strGravityWellGeneratorTech,
    strCloakGeneratorTech,
    strRepairTech,
    strSalvageTech,
    strDFGFTech,
    strDefenseFighterTech,

    strWeaponHeading,
    strConstuctionHeading,
    strInterdictionHeading,
    strSupportHeading,

    strR1NewAlloysinfo,
    strR1MassDrive1Ktinfo,
    strR1CoolingSystemsinfo,
    strR1CloakFighterinfo,
    strR1TargetingSystemsinfo,
    strR1PlasmaWeaponsinfo,
    strR1Chassis1info,
    strR1MassDrive10Ktinfo,
    strR1MediumGunsinfo,
    strR1MineLayerTechinfo,
    strR1Chassis2info,
    strR1AdvancedCoolingSystemsinfo,
    strR1MassDrive100Ktinfo,
    strR1FireControlinfo,
    strR1SupportRefuelTechinfo,
    strR1AdvanceTacticalSupportinfo,
    strR1IonWeaponsinfo,
    strR1DDDFTechinfo,
    strR1Chassis3info,
    strR1MassDrive1Mtinfo,
    strR1AdvancedFireControlinfo,
    strR1MissileWeaponsinfo,
    strR1ConstructionTechinfo,
    strR1HeavyGunsinfo,
    strR1ProximityDetectorinfo,
    strR1SensorsArrayTechinfo,
    strR1GravityWellGeneratorTechinfo,
    strR1CloakGeneratorTechinfo,
    strR1RepairTechinfo,
    strR1SalvageTechinfo,
    strR1DFGFTechinfo,
    strR1DefenseFighterTechinfo,

    strR2NewAlloysinfo,
    strR2MassDrive1Ktinfo,
    strR2CoolingSystemsinfo,
    strR2CloakFighterinfo,
    strR2TargetingSystemsinfo,
    strR2PlasmaWeaponsinfo,
    strR2Chassis1info,
    strR2MassDrive10Ktinfo,
    strR2MediumGunsinfo,
    strR2MineLayerTechinfo,
    strR2Chassis2info,
    strR2AdvancedCoolingSystemsinfo,
    strR2MassDrive100Ktinfo,
    strR2FireControlinfo,
    strR2SupportRefuelTechinfo,
    strR2AdvanceTacticalSupportinfo,
    strR2IonWeaponsinfo,
    strR2DDDFTechinfo,
    strR2Chassis3info,
    strR2MassDrive1Mtinfo,
    strR2AdvancedFireControlinfo,
    strR2MissileWeaponsinfo,
    strR2ConstructionTechinfo,
    strR2HeavyGunsinfo,
    strR2ProximityDetectorinfo,
    strR2SensorsArrayTechinfo,
    strR2GravityWellGeneratorTechinfo,
    strR2CloakGeneratorTechinfo,
    strR2RepairTechinfo,
    strR2SalvageTechinfo,
    strR2DFGFTechinfo,
    strR2DefenseFighterTechinfo,

    strAbrevAdvanceSupportFrigate,
    strAbrevAttackBomber,
    strAbrevCarrier,
    strAbrevCloakedFighter,
    strAbrevCloakGenerator,
    strAbrevDDDFrigate,
    strAbrevDefenseFighter,
    strAbrevDFGFrigate,
    strAbrevGravWellGenerator,
    strAbrevHeavyCorvette,
    strAbrevHeavyCruiser,
    strAbrevHeavyDefender,
    strAbrevHeavyInterceptor,
    strAbrevIonCannonFrigate,
    strAbrevLightCorvette,
    strAbrevLightDefender,
    strAbrevLightInterceptor,
    strAbrevMinelayerCorvette,
    strAbrevMissileDestroyer,
    strAbrevMothership,
    strAbrevMultiGunCorvette,
    strAbrevProbe,
    strAbrevProximitySensor,
    strAbrevRepairCorvette,
    strAbrevResearchShip,
    strAbrevResourceCollector,
    strAbrevResourceController,
    strAbrevSalCapCorvette,
    strAbrevSensorArray,
    strAbrevStandardDestroyer,
    strAbrevStandardFrigate,
    strAbrevDrone,
    strAbrevTargetDrone,
    strAbrevHeadShotAsteroid,
    strAbrevCryoTray,
    strAbrevP1Fighter,
    strAbrevP1IonArrayFrigate,
    strAbrevP1MissileCorvette,
    strAbrevP1Mothership,
    strAbrevP1StandardCorvette,
    strAbrevP2AdvanceSwarmer,
    strAbrevP2FuelPod,
    strAbrevP2Mothership,
    strAbrevP2MultiBeamFrigate,
    strAbrevP2Swarmer,
    strAbrevP3Destroyer,
    strAbrevP3Frigate,
    strAbrevP3Megaship,
    strAbrevFloatingCity,
    strAbrevCargoBarge,
    strAbrevMiningBase,
    strAbrevResearchStation,
    strAbrevJunkYardDawg,
    strAbrevJunkYardHQ,
    strAbrevGhostship,
    strAbrevJunk_LGun,
    strAbrevJunk_SGun,
    strAbrevResearchStationBridge,
    strAbrevResearchStationTower,

    strCanBuild,

    strDELTA_FORMATION,
    strBROAD_FORMATION,
    strDELTA3D_FORMATION,
    strCLAW_FORMATION,
    strWALL_FORMATION,
    strSPHERE_FORMATION,
    strPICKET_FORMATION,

    strPARADE_FORMATION,

    strCreatingRoom,
    strRoomCreated,
    strQueryingChat,
    strConnectingToChat,
    strConnectedToChat,
    strStartingChat,
    strCreatedChat,
    strSendingLogin,
    strChangingPassword,
    strCreatingUser,
    strRequestingToJoin,
    strConnectedWon,
    strLoginFailed,
    strHitCancelAgain,
    strPasswordChangeSuccess,
    strPasswordChangeFailed,
    strNewUserCreated,
    strDuplicateUser,
    strUserNotFound,
    strInvalidName,
    strUnknownAuthReply,
    strFailedToCreateUser,
    strFailedToChat,
    strHitCancelContinue,
    strJoinRequestGranted,
    strJoinRequestDenied,
    strWonOffline,
    strServerDown,

    strKeyAlreadyInUse,
    strBadKey,
    strLightweightBadKey,
    strBadKeyExpired,
    strBadKeyLockedOut,
    strBadKeyBetaKeyRequired,
    strBadKeyBetaKeyNotAllowed,
    strNoCDKey,

    strFailedToCreateChat,
    strFailedToConnectToDirServer,
    strCantJoinOwnGame,
    strErrorCantFindGame,
    strIncorrectPassword,
    strCaptainDisolvedGame,
    strNoInternetTCPIP,
    strNoLanIPXorTCPIP,
    strProtocalIPXLAN,
    strProtocalTCPIPLAN,
    strAuthCRCFailed,
    strErrorStillWaitingVersionInfo,
    strMinNumPlayersRequired,
    strMustBeInRoomToCreateGame,
    strMustBeInRoomToCreateGame2,

    strCreatingGame,
    strInvalidRoomPassword,
    strErrorUserAlreadyExists,
    strErrorRoomFull,
    strNeedLatestVersion,
    strDownloadingPatch,
    strErrorGameAlreadyExists,
    strCreatedGame,
    strDroppedOut,
    strQuit,
    strErrorTypingPassword,
    strPasswordProtected,
    strInProgress,
    strDiffVersion,
    strErrorRoomAlreadyExists,
    strNoRoom,
    strDifferentVersions,
    strMustUpgradeToSameVersion,
    strChatDisconnected,

    strYouMustTypeInGameName,
    strAtLeast2Chars,
    strMustBeAtLeast2Chars,
    strErrorInSaveGameName,
    strErrorInvalidSaveGameFile,
    strErrorInvalidSaveGameFileVersion,

    strStartingGame,
    strDetectedUserBehindFirewall,
    strStartingRoutingServer,
    strTellingPlayersToConnectToMe,
    strConnectingToRoutingServer,
    strPlayerJoined,
    strConnectingToCaptain,
    strTellingPlayersConnectRoutServ,

    strPatchStartingDownload,
    strPatchDownloading,
    strPatchGeneralError,
    strPatchUnableCreateFile,
    strPatchUnableWriteFile,
    strPatchUserAbort,
    strPATCHFAIL_UNABLE_TO_CONNECT,
    strPATCHFAIL_ERROR_SENDING_REQUEST,
    strPATCHFAIL_ERROR_RECEIVING_HTTP_HEADER,
    strPATCHFAIL_INVALID_FILE_LENGTH,
    strPATCHFAIL_ERROR_RECEIVING_PATCH,
    strPATCHFAIL_UNABLE_TO_START_DOWNLOAD_THREAD,
    strPATCHFAIL_INVALID_STATUS_REPLY,
    strTryLaterDownloadManually,

    strWhisperedMessage,
    strHasJoined,
    strHasLeft,

    strChannelNameHeading,
    strChannelDescHeading,
    strChannelNumberHeading,

    strGameNameHeading,
    strGamePingHeading,
    strGameNumPlayerHeading,
    strGameMapHeading,

    strCustomMapAutoupload,
    strCustomMapAutodownload,

    strVersion,

    strAsksToFormAlliance,
    strWants,
    strToJoin,
    strAnd,
    strAllianceFormed,
    strHasBrokenAlliance,
    strAllianceBroken,
    strAllianceRequest,
    strAllianceConfirm,
    strAskForPermision,

    strComputerName,

    strFirepower,
    strCoverage,
    strManeuver,
    strArmor,
    strTopSpeed,
    strMass,

    strVeryLow,
    strLow,
    strMedium,
    strHigh,
    strVeryHigh,
    strCoverageUnits,

    strFightersCorvettesDocked,

    strSay,
    strToAllies,
    strRUAmount,

    strTutorialTip,

    strPlayersAllied,
    strResourcesRes,
    strGas,
    strDust,
    strRock,
    strNonCombatShips,
    strStrikeCraft,
    strCapitalShips,

    strPingTO0,
    strPingTO1,
    strPingTO2,
    strPingTO3,
    strPingTO4,
    strPingTORC,

    strSaveSinglePlayerLevel1,
    strSavedGame,
    strRecordingGame,
    strQuickSave,

    strCaptainTransfering,

    strEndOfBuffer,
    strStartOfBuffer,

    strObjComplete,
    strObjIncomplete,
    strobjSecondary,

    strkbNEXT_FORMATION,
    strkbBUILD_MANAGER,
    strkbPREVIOUS_FOCUS,
    strkbNEXT_FOCUS,
    strkbDOCK,
    strkbSELECT_ALL_VISIBLE,
    strkbFOCUS,
    strkbRESEARCH_MANAGER,
    strkbHARVEST,
    strkbMOVE,
    strkbNEXT_TACTIC,
    strkbPREVIOUS_TACTIC,
    strkbSCUTTLE,
    strkbSHIP_SPECIAL,
    strkbTACTICAL_OVERLAY,
    strkbMOTHERSHIP,
    strkbKAMIKAZE,
    strkbCANCEL_ORDERS,
    strkbLAUNCH_MANAGER,
    strkbTOTAL_COMMANDS,

    strAKEY,
    strBKEY,
    strCKEY,
    strDKEY,
    strEKEY,
    strFKEY,
    strGKEY,
    strHKEY,
    strIKEY,
    strJKEY,
    strKKEY,
    strLKEY,
    strMKEY,
    strNKEY,
    strOKEY,
    strPKEY,
    strQKEY,
    strRKEY,
    strSKEY,
    strTKEY,
    strUKEY,
    strVKEY,
    strWKEY,
    strXKEY,
    strYKEY,
    strZKEY,
    strBACKSPACEKEY,
    strTABKEY,
    strARRLEFT,
    strARRRIGHT,
    strARRUP,
    strARRDOWN,
    strENDKEY,
    strLBRACK,
    strRBRACK,
    strCAPSLOCKKEY,
    strSPACEKEY,
    strENTERKEY,
    strHOMEKEY,
    strPAGEDOWNKEY,
    strPAGEUPKEY,
    strBACKSLASHKEY,
    strPAUSEKEY,
    strSCROLLKEY,
    strPRINTKEY,
    strINSERTKEY,
    strDELETEKEY,
    strLESSTHAN,
    strGREATERTHAN,
    strTILDEKEY,
    strNUMPAD0,
    strNUMPAD1,
    strNUMPAD2,
    strNUMPAD3,
    strNUMPAD4,
    strNUMPAD5,
    strNUMPAD6,
    strNUMPAD7,
    strNUMPAD8,
    strNUMPAD9,
    strNUMMINUSKEY,
    strNUMPLUSKEY,
    strNUMSTARKEY,
    strNUMSLASHKEY,
    strNUMDOTKEY,
    strMINUSKEY,
    strPLUSKEY,
    strF1KEY,
    strF2KEY,
    strF3KEY,
    strF4KEY,
    strF5KEY,
    strF6KEY,
    strF7KEY,
    strF8KEY,
    strF9KEY,
    strF10KEY,
    strF11KEY,
    strF12KEY,

    strCommandToBind,
    strKeyBound,
    strNoKeyBound,

    strMissingCD,
    strInvalidCD,

    strGDIGeneric0,
    strGDIGeneric1,
    strGDIGenericRenderer,

    strOPCountdown0,
    strOPCountdown1,
    strOPCountdown2,
    strOPFailed0,
    strOPFailed1,

    strDefaultPlayerName,

    strStatsDiedStats,
    strStatsGameEndStats,
    strStatsPlayerName,
    strStatsPlayerRace,
    strStatsTimeOfDeath,
    strStatsDeathByDropout,
    strStatsDeathByShipCapture,
    strStatsDeathByLossOfMission,
    strStatsDeathStillAlive,
    strStatsRUsStart,
    strStatsRUsCollected,
    strStatsRUsSpent,
    strStatsRUsGiven,
    strStatsRUsReceived,
    strStatsRUsInjected,
    strStatsRUsByBounties,
    strStatsRUsGenerated,
    strStatsCurrentRUs,
    strStatsTotalDmgAgainstPlayer,
    strStatsTotalAcquiredShips,
    strStatsTotalAcqShipsByType,
    strStatsTotalAcqShipsByClass,
    strStatsTotalKills,
    strStatsKilled,
    strStatsTotalLosses,
    strStatsLost,

    strSVCost,
    strSVRUs,

    strFailedToStartRoutingServer,
    strServerLoadHeading,
    strServerReliabilityHeading,

    strStatsBadResUnitsBounds,
    strStatsBadResUnitTotals,
    strStatsBadShipBounds,
    strStatsBadShipCostTotals,
    strStatsBadShipsAcquiredTotals,
    strStatsBadShipsKilledTotals,
    strStatsBadShipsLostTotals,
    strStatsBadShipsAcquiredClassTotals,
    strStatsBadShipsKilledClassTotals,
    strStatsBadShipsLostClassTotals,

    strCommandIgnoreOn,
    strCommandIgnoreOff,
    strCommandKickCaptain,
    strCommandKickPlayer,
    strCommandBanOn,
    strCommandBanOff,
    strCommandLimit,
    strCommandLimitOff,

    strCheatDetect,

    NumStrings
} strGamesMessages;

#define strShipOffset         strAdvanceSupportFrigate
#define strClassOffset        strCLASS_Mothership
#define strTechOffset         strNewAlloys
#define strTechHeadingOffset  strWeaponHeading
#define strTechInfoOffsetR1   strR1NewAlloysinfo
#define strTechInfoOffsetR2   strR2NewAlloysinfo
#define strShipAbrevOffset    strAbrevAdvanceSupportFrigate
#define strFormationOffset    strDELTA_FORMATION
#define strShipStatNameOffset strFirepower
#define strKeyCommandOffset   strkbNEXT_FORMATION

/*=============================================================================
    Data:
=============================================================================*/

extern char *MessageStrings[NumStrings];

/*=============================================================================
    Macros:
=============================================================================*/

#define strGetString(string) (MessageStrings[string])


#endif //___STRINGS_ONLY_H

