/* VAR_Technologies */
#define		Tech_NewAlloys					0
#define		Tech_MassDrive1Kt				1
#define		Tech_CoolingSystems				2
#define		Tech_CloakDefenseFighter		3
#define		Tech_TargetingSystems			4
#define		Tech_PlasmaWeapons				5
#define		Tech_Chassis1					6
#define		Tech_MassDrive10Kt				7
#define		Tech_MediumGuns					8
#define		Tech_MineLayerTech				9
#define		Tech_Chassis2					10
#define		Tech_AdvancedCoolingSystems		11
#define		Tech_MassDrive100Kt				12
#define		Tech_FireControl				13
#define		Tech_SupportRefuelTech			14
#define		Tech_AdvanceTacticalSupport		15
#define		Tech_IonWeapons					16
#define		Tech_DDDFDFGFTech				17
#define		Tech_Chassis3					18
#define		Tech_MassDrive1Mt				19
#define		Tech_AdvancedFireControl		20
#define		Tech_MissileWeapons				21
#define		Tech_ConstructionTech			22
#define		Tech_HeavyGuns					23
#define		Tech_ProximityDetector			24
#define		Tech_SensorsArrayTech			25
#define		Tech_GravityWellGeneratorTech	26
#define		Tech_CloakGeneratorTech			27
#define		Tech_RepairTech					28
#define		Tech_SalvageTech				29

