/* VAR_Technologies */
#define		04_FighterProduction 					0
#define		05_FighterDrive				1
#define		Tech_CoolingSystems				2
#define		06_CloakDefenseFighter		3
#define		08_FastTrackingTurrets			4
#define		09_PlasmaBombLauncher				5
#define		10_HeavyFighterChassis					6
#define		11_CorvetteDrive				7
#define		12_HeavyCorvetteUpgrade					8
#define		13_MinelayingTech				9
#define		14_CorvetteChasis					10
#define		Tech_AdvancedCoolingSystems		11
#define		15_CapitalShipDrive				12
#define		16_DefenderSubSystems				13
#define		17_CorvetteProduction			14
#define		Tech_AdvanceTacticalSupport		15
#define		18_IonCannons					16
#define		19_DDDFDFGFTech				17
#define		21_CapitalShipChassis					18
#define		22_SuperCapShipDrive				19
#define		Tech_AdvancedFireControl		20
#define		23_GuidedMissiles				21
#define		Tech_ConstructionTech			22
#define		24_HeavyGuns					23
#define		25_ProximityDetector			24
#define		26_SensorsArrayTech			25
#define		27_GravityWellGeneratorTech	26
#define		28_CloakGeneratorTech			27
#define		29_SuperHeavyChassis					28
#define		30_CapitalShipProduction				29

