/* VAR_Ships */
#define AdvanceSupportFrigate           0
#define AttackBomber                    1
#define Carrier                         2
#define CloakedFighter                  3
#define CloakGenerator                  4
#define DDDFrigate                      5
#define DefenseFighter                  6
#define DFGFrigate                      7
#define GravWellGenerator               8
#define HeavyCorvette                   9
#define HeavyCruiser                    10
#define HeavyDefender                   11
#define HeavyInterceptor                12
#define IonCannonFrigate                13
#define LightCorvette                   14
#define LightDefender                   15
#define LightInterceptor                16
#define MinelayerCorvette               17
#define MissileDestroyer                18
#define Mothership                      19
#define MultiGunCorvette                20
#define Probe                           21
#define ProximitySensor                 22
#define RepairCorvette                  23
#define ResearchShip                    24
#define ResourceCollector               25
#define ResourceController              26
#define SalCapCorvette                  27
#define SensorArray                     28
#define StandardDestroyer               29
#define StandardFrigate                 30
#define Drone                           31
#define TargetDrone                     32
#define HeadShotAsteroid                33      // Headshot asteroid is now a ship!
#define CryoTray                        34      // CryoTray is now a ship!
#define P1Fighter                       35
#define P1IonArrayFrigate               36
#define P1MissileCorvette               37
#define P1Mothership                    38
#define P1StandardCorvette              39
#define P2AdvanceSwarmer                40
#define P2FuelPod                       41
#define P2Mothership                    42
#define P2MultiBeamFrigate              43
#define P2Swarmer                       44
#define P3Destroyer                     45
#define P3Frigate                       46
#define P3Megaship                      47
#define FloatingCity                    48
#define CargoBarge                      49
#define MiningBase                      50
#define ResearchStation                 51
#define JunkYardDawg                    52
#define JunkYardHQ                      53
#define Ghostship                       54
#define Junk_LGun                       55
#define Junk_SGun                       56
#define ResearchStationBridge           57
#define ResearchStationTower            58

