
#define E_PATCHER_NAME "Homeworld Patcher"
#define E_PATCH_FINISHED_RUN_HW "Patch Finished.  Do you wish to run Homeworld?"
#define E_PATCHSUCCESS  "Patch successful"
#define E_COPYFILESFAILED "Patch failed - file %s not copied to %s"
#define E_COULDNOTLOCATEHW "Patch failed - could not locate Homeworld"
#define E_UNKNOWN_ERROR "Patch failed - general failure"
#define E_LOCATE_HOMEWORLD "Locate where Homeworld.exe is installed"

#define F_PATCHER_NAME "Patch Homeworld"
#define F_PATCH_FINISHED_RUN_HW "Installation du patch terminée. Souhaitez-vous lancer Homeworld ?"
#define F_PATCHSUCCESS  "Installation du patch réussie"
#define F_COPYFILESFAILED "L'installation du patch a échoué - fichier %s non copié sur  %s"
#define F_COULDNOTLOCATEHW "L'installation du patch a échoué : impossible de localiser Homeworld"
#define F_UNKNOWN_ERROR "L'installation du patch a échoué : erreur générale"
#define F_LOCATE_HOMEWORLD "Localiser l'emplacement du fichier Homeworld.exe"

#define G_PATCHER_NAME "Homeworld - Patch-Programm"
#define G_PATCH_FINISHED_RUN_HW "Patch abgeschlossen.  Möchten Sie jetzt Homeworld starten?"
#define G_PATCHSUCCESS  "Patch erfolgreich."
#define G_COPYFILESFAILED "Patch-Fehler - Die Datei %s konnte nicht nach %s kopiert werden."
#define G_COULDNOTLOCATEHW "Patch-Fehler - Homeworld konnte nicht gefunden werden."
#define G_UNKNOWN_ERROR "Patch-Fehler - Allgemeiner Fehler."
#define G_LOCATE_HOMEWORLD "Suchen, wo HOMEWORLD.EXE installiert ist."

#define S_PATCHER_NAME "Arreglo (patch) de Homeworld"
#define S_PATCH_FINISHED_RUN_HW "Arreglo finalizado. ¿Deseas ejecutar Homeworld?"
#define S_PATCHSUCCESS  "Arreglo completado correctamente"
#define S_COPYFILESFAILED "Ha fallado el arreglo; el archivo %s no se ha copiado en %s"
#define S_COULDNOTLOCATEHW "Ha fallado el arreglo; no se encuentra Homeworld"
#define S_UNKNOWN_ERROR "Ha fallado el arreglo; fallo general"
#define S_LOCATE_HOMEWORLD "Busca el archivo Homeworld.exe"

#define I_PATCHER_NAME "Aggiornamento di Homeworld"
#define I_PATCH_FINISHED_RUN_HW "Aggiornamento completato.  Lanciare Homeworld?"
#define I_PATCHSUCCESS  "Aggiornamento riuscito"
#define I_COPYFILESFAILED "Aggiornamento non riuscito - file %s non copiato in %s"
#define I_COULDNOTLOCATEHW "Aggiornamento non riuscito - impossibile trovare Homeworld"
#define I_UNKNOWN_ERROR "Aggiornamento non riuscito - errore generico"
#define I_LOCATE_HOMEWORLD "Trovare la directory in cui è installato Homeworld.exe"

